### ISSUE TITLE
Bug Fig 1.20: fig.run() not working.

### ISSUE THREAD

**Issue by raguay** [withfig/fig-issues#1]
When making an application for fig, the `fig.run()` command gives the command line to the shell and then pieces of it afterwards in an unpredictable order/way. You can see the trail of partial commands in the attached picture:
![GlitchInFig](https://user-images.githubusercontent.com/2487495/95194828-f1388480-07ff-11eb-9409-63258cf4fbaa.png)

**Comment by falky97** [comment]
@mattschrage This has been fixed as of v1.0.21. We changed the way we did fig.insert. We did this for fig.run too however, have reverted back to the old way. Future versions may include the new way.
