### ISSUE TITLE
Fig Sidebar shows on Secondary Display When you have multiple displays 

### ISSUE THREAD

**Issue by dipakparmar** [withfig/fig-issues#2]
**Describe the bug**
In Extended Display mode if the Terminal is open on Primary Screen and the Secondary screen is placed on the right of the primary screen Fig sidebar shows on Secondary Display.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect at least two monitors/screens
2. Make sure fig is running if not start it.
3. Open Terminal on any Screen.
4. Move the terminal to the left screen of another screen
eg. 
![image](https://user-images.githubusercontent.com/24366206/95283429-a6733880-0810-11eb-9fb8-624797e4eb53.png)

**Expected behaviour**
Fig bar should stick to the Terminal Screen

**Screenshots**
![image](https://user-images.githubusercontent.com/24366206/95283533-e89c7a00-0810-11eb-8bac-7cd8455af3ab.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.17
 - Terminal: mac default Shell, iTerm2
 - Fig Version 1.0.20

**Additional context**
- current workaround: use terminal on-screen which doesn't have any screen right to it.

**Comment by dipakparmar** [comment]
Found a similar issue with the beta feature: autocomplete show on the left screen

![image](https://user-images.githubusercontent.com/24366206/95373758-491fcb80-0892-11eb-922e-b5dd8d318792.png)

**Comment by falky97** [comment]
![IMG_0770](https://user-images.githubusercontent.com/4949076/96962628-11cd3380-14bc-11eb-9719-ba6cd4f3f7fa.jpeg)
Thought we had fixed it but the error persists!!

**Comment by dipakparmar** [comment]
@falky97 Looks like this is fixed in 1.0.27 👏🏻

**Comment by falky97** [comment]
We tried to fix it, we thought we did but we weren't 100% sure. We will leave this open for the time being and see if more people face the issue. If not, will close it in a couple of weeks.

Glad it's better for you!

**Comment by dipakparmar** [comment]
Got back the same issue again. But this time after mac update, just updated to Catalina 10.15.7. 😢

**Comment by dipakparmar** [comment]
Closing it, as sidebar feature is legacy now.
