### ISSUE TITLE
Fig cwd doesn't update after whitelisting process

### ISSUE THREAD

**Issue by dipakparmar** [withfig/fig-issues#6]
I have whitelisted a process from PowerShell zsh theme!

Changing the directory in the terminal doesn't update the CWD for fig. results in incomplete are for `/`

![image](https://user-images.githubusercontent.com/24366206/99155355-0a88e800-266c-11eb-8e41-759776e586b3.png)

**Comment by falky97** [comment]
Thanks Dipak! We are aware and are fixing this fr next build (v1.0.29)

Brendan Falk
Co-founder & CEO @ Fig
brendan@withfig.com
(857) 800-1383

**Comment by dipakparmar** [comment]
Seems this fixed in v1.0.30

Thank you guys!

**Comment by falky97** [comment]
Sounds good! Making some more changes in v31 so we can get powerlevel 10k working. Thanks Dipak!
